-- Database #656: Portal navigation vocabulary.
--
-- Stores the deterministic vocabulary generated by
-- `scripts/generate_portal_navigation_vocabulary.py` from two receipted,
-- read-only sources:
--
--   * the platform static taxonomy pinned at
--     `aca2d4f2a905e97867942a78be75c5daea4fde5e`
--     (`isic`, `cpc`, `ilcd-flow-categorization`, `ilcd-locations`);
--   * the frozen TianGong LCA Database snapshot
--     (`data/tiangong_lca_data/ILCDLocations.xml`), used only for the Chinese
--     province/city codes the pinned vocabulary does not carry.
--
-- The seeded rows are generated output. Regenerate them with the script rather
-- than editing them: this migration only owns the schema, the manifest table and
-- the runtime guards that keep the seeded rows bound to
-- `contracts/portal/navigation-vocabulary.json`.
begin;

set local lock_timeout = '5s';
set local statement_timeout = '60s';

do $portal_navigation_role_guard$
begin
  if not exists (
    select 1
    from pg_catalog.pg_roles
    where rolname = 'api_internal_executor'
      and not rolcanlogin
      and not rolbypassrls
      and not rolsuper
      and not rolreplication
  ) or not exists (
    select 1
    from pg_catalog.pg_roles
    where rolname = 'portal_public_executor'
      and not rolcanlogin
      and not rolbypassrls
      and not rolsuper
      and not rolreplication
  ) then
    raise exception 'Portal navigation executor prerequisite is unsafe'
      using errcode = '42501';
  end if;
end
$portal_navigation_role_guard$;

create table private.portal_navigation_contract_v1 (
  contract_version smallint primary key,
  manifest_schema text not null,
  asset_sha256 text not null,
  seed_sha256 text not null,
  node_count integer not null,
  created_by_migration text not null,
  constraint portal_navigation_contract_version_v1_chk
    check (contract_version = 1),
  constraint portal_navigation_contract_schema_v1_chk
    check (manifest_schema = 'portal.navigation-vocabulary-manifest.v1'),
  constraint portal_navigation_contract_asset_v1_chk
    check (asset_sha256 ~ '^[0-9a-f]{64}$'),
  constraint portal_navigation_contract_seed_v1_chk
    check (seed_sha256 ~ '^[0-9a-f]{64}$'),
  constraint portal_navigation_contract_count_v1_chk
    check (node_count between 1 and 100000),
  constraint portal_navigation_contract_migration_v1_chk
    check (created_by_migration ~ '^[0-9]{14}$')
);

alter table private.portal_navigation_contract_v1 owner to postgres;
alter table private.portal_navigation_contract_v1 enable row level security;
alter table private.portal_navigation_contract_v1 force row level security;

create table private.portal_navigation_node_v1 (
  node_id text primary key
    check (node_id ~ '^[a-z][a-z0-9-]*:[!-~]{1,96}$'),
  parent_node_id text
    references private.portal_navigation_node_v1(node_id)
    on update restrict on delete restrict,
  code text not null
    check (pg_catalog.length(code) between 1 and 64),
  taxonomy text not null
    check (taxonomy ~ '^[a-z][a-z0-9-]{1,48}$'),
  dimension text not null
    check (dimension in ('classification', 'geography')),
  source_index_path text,
  source_file text,
  -- Source codes that address this exact node in another vocabulary; see
  -- `contracts/portal/navigation-vocabulary.json`.
  alias_codes text[] not null default '{}'::text[],
  labels jsonb not null
    check (
      pg_catalog.jsonb_typeof(labels) = 'object'
      and pg_catalog.jsonb_typeof(labels -> 'en') = 'string'
      and pg_catalog.jsonb_typeof(labels -> 'zh-CN') = 'string'
      and pg_catalog.jsonb_typeof(labels -> 'de') = 'string'
      and pg_catalog.jsonb_typeof(labels -> 'fr') = 'string'
    ),
  label_strategy jsonb not null
    check (
      pg_catalog.jsonb_typeof(label_strategy) = 'object'
      and pg_catalog.jsonb_typeof(label_strategy -> 'en') = 'string'
      and pg_catalog.jsonb_typeof(label_strategy -> 'zh-CN') = 'string'
      and pg_catalog.jsonb_typeof(label_strategy -> 'de') = 'string'
      and pg_catalog.jsonb_typeof(label_strategy -> 'fr') = 'string'
    ),
  constraint portal_navigation_node_root_v1_chk
    check (parent_node_id is distinct from node_id)
);

alter table private.portal_navigation_node_v1 owner to postgres;
alter table private.portal_navigation_node_v1 enable row level security;
alter table private.portal_navigation_node_v1 force row level security;

-- One index serves both the paginated immediate-children scan and the
-- `hasChildren` probe, so no stored child-count flag can drift.
create index portal_navigation_node_parent_v1_idx
  on private.portal_navigation_node_v1 (dimension, parent_node_id, node_id);
create index portal_navigation_node_taxonomy_v1_idx
  on private.portal_navigation_node_v1 (dimension, taxonomy, code);

create policy portal_navigation_node_portal_select_v1
on private.portal_navigation_node_v1
for select
to portal_public_executor
using (true);

create policy portal_navigation_node_internal_all_v1
on private.portal_navigation_node_v1
for all
to api_internal_executor
using (true)
with check (true);

create policy portal_navigation_contract_internal_select_v1
on private.portal_navigation_contract_v1
for select
to api_internal_executor
using (contract_version = 1);

revoke all on table private.portal_navigation_contract_v1
  from public, anon, authenticated, service_role, portal_public_executor;
revoke all on table private.portal_navigation_node_v1
  from public, anon, authenticated, service_role;
grant select on table private.portal_navigation_contract_v1
  to api_internal_executor;
grant select (
  node_id, parent_node_id, code, taxonomy, dimension,
  source_index_path, source_file, alias_codes, labels, label_strategy
) on table private.portal_navigation_node_v1
  to portal_public_executor;
grant select, insert, update, delete on table private.portal_navigation_node_v1
  to api_internal_executor;

grant api_internal_executor to postgres;
grant create on schema private to api_internal_executor;
set role api_internal_executor;

create function private.assert_portal_navigation_contract_v1()
returns void
language plpgsql
stable
parallel safe
security definer
set search_path = ''
set row_security = 'on'
as $function$
declare
  v_version smallint;
  v_expected integer;
  v_seeded integer;
  v_root text;
begin
  select contract.contract_version,
    contract.node_count
  into v_version, v_expected
  from private.portal_navigation_contract_v1 as contract
  where contract.contract_version = 1;

  if v_version is distinct from 1 then
    raise exception 'Portal navigation contract is absent'
      using errcode = '55000';
  end if;

  -- The check runs inside the seed migration itself, which is the only moment
  -- the vocabulary is exactly the seeded asset. Later migrations add the
  -- projection writer, and from then on a container for an unknown or
  -- unclassified value may be created on demand, so the live total may exceed
  -- the manifest while the seeded rows can never be removed (the membership rows
  -- reference them with ON DELETE RESTRICT).
  select pg_catalog.count(*)::integer
  into v_seeded
  from private.portal_navigation_node_v1 as node;

  if v_seeded < v_expected then
    raise exception 'Portal navigation vocabulary is incomplete'
      using errcode = '55000';
  end if;

  foreach v_root in array array[
    'class:isic', 'class:cpc', 'class:elementary', 'geo:unmapped'
  ]
  loop
    if not exists (
      select 1
      from private.portal_navigation_node_v1 as node
      where node.node_id = v_root
    ) then
      raise exception 'Portal navigation vocabulary root % is absent', v_root
        using errcode = '55000';
    end if;
  end loop;
end
$function$;

comment on function private.assert_portal_navigation_contract_v1() is
  'Fails closed when the Portal navigation manifest row, its seeded vocabulary baseline, or a required taxonomy root is missing.';

revoke all on function private.assert_portal_navigation_contract_v1()
  from public, anon, authenticated, service_role, portal_public_executor;
-- `postgres` owns database-side verification and the seed migration re-runs this
-- same guard; every browser-facing role stays revoked.
grant execute on function private.assert_portal_navigation_contract_v1()
  to api_internal_executor, postgres;

reset role;

revoke create on schema private from api_internal_executor;
revoke api_internal_executor from postgres;

commit;
